/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["PlusJakartaSans-Regular", "System"],
        display: ["PlusJakartaSans-ExtraBold", "System"],
        "display-bold": ["PlusJakartaSans-Bold", "System"],
        "display-semibold": ["PlusJakartaSans-SemiBold", "System"],
        mono: ["Geist-Medium", "System"],
        "mono-semibold": ["Geist-SemiBold", "System"],
      },
      colors: {
        // Celestial Cinema Design Tokens
        primary: "#030014",
        secondary: "#151312",
        background: "#141315",
        surface: {
          DEFAULT: "#141315",
          dim: "#141315",
          bright: "#3a393b",
          variant: "#363436",
        },
        "surface-container": {
          lowest: "#0f0e10",
          low: "#1c1b1d",
          DEFAULT: "#201f21",
          high: "#2b292c",
          highest: "#363436",
        },
        "on-surface": "#e6e1e4",
        "on-surface-variant": "#cac5cd",
        "on-background": "#e6e1e4",
        "primary-container": "#030014",
        "on-primary-container": "#7a7290",
        "primary-text": "#cbc2e3",
        "on-primary": "#332c47",
        "secondary-container": "#4c4847",
        "on-secondary-container": "#bdb7b5",
        outline: {
          DEFAULT: "#938f97",
          variant: "#48454d",
        },
        "surface-tint": "#cbc2e3",
        "inverse-surface": "#e6e1e4",
        "inverse-on-surface": "#313032",
        "inverse-primary": "#625a77",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        // Accent colors
        accent: "#AB8BFF",
        "accent-light": "#C4ABFF",
        "accent-dark": "#7B5FD4",
        "accent-purple": "#AB8BFF",
        // Utility colors
        gold: "#FFD700",
        "gold-dark": "#B8960F",
        "rating-green": "#4CAF50",
        "rating-yellow": "#FFC107",
        "rating-red": "#F44336",
        // Legacy aliases
        light: {
          100: "#D6C7FF",
          200: "#A8B5DB",
          300: "#9CA4AB",
        },
        dark: {
          100: "#221F3D",
          200: "#0F0D23",
          300: "#1A1730",
        },
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "16px",
        "3xl": "24px",
        "4xl": "32px",
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "800", letterSpacing: -1 }],
        "display-lg-mobile": ["32px", { lineHeight: "38px", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: 1 }],
        "mono-label": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        hero: ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "section-title": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        caption: ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "12px",
        "margin-edge": "16px",
        13: "52px",
        15: "60px",
        18: "72px",
        22: "88px",
      },
      boxShadow: {
        glow: "0 0 20px rgba(171, 139, 255, 0.3)",
        "glow-sm": "0 0 10px rgba(171, 139, 255, 0.2)",
        "glow-gold": "0 0 15px rgba(255, 215, 0, 0.25)",
        card: "0 4px 12px rgba(0, 0, 0, 0.4)",
        "card-lg": "0 8px 24px rgba(0, 0, 0, 0.5)",
      },
    },
  },
  plugins: [],
};
